"""
Custom ELI Agent: Tvshowagent
Generated by Agent Creator Wizard.

Purpose  : tvshowagent
Triggers : tvshows
Persona  : hg
"""
from __future__ import annotations

from typing import Any, Dict
from eli.cognition.agent_bus import _BaseAgent, AgentResult


class Tvshowagent(_BaseAgent):
    name = "tvshowagent"
    timeout_s = 5.0

    # Configuration derived from wizard answers
    _purpose = "tvshowagent"
    _triggers_info = "tvshows"
    _persona = "hg"

    def run(
        self,
        user_input: str,
        intent: Dict[str, Any],
        session_id: str,
        user_id: str,
    ) -> AgentResult:
        """Run the custom agent logic."""
        try:
            # Keyword-based trigger check
            low = user_input.lower()
            trigger_words = [
                w.strip().lower()
                for w in self._triggers_info.replace(",", " ").split()
                if len(w.strip()) > 2
            ]
            if trigger_words and not any(tw in low for tw in trigger_words[:8]):
                return AgentResult(
                    agent=self.name,
                    ok=True,
                    confidence=0.0,
                    data={"skipped": True, "reason": "no trigger match"},
                )

            # Build a context block for the LLM
            context = (
                f"Agent: {self.name}\n"
                f"Purpose: {self._purpose}\n"
                f"Persona/output style: {self._persona}\n"
                f"User query: {user_input}"
            )
            return AgentResult(
                agent=self.name,
                ok=True,
                confidence=0.65,
                data={
                    "memory_context": context,
                    "agent_note": f"Custom agent {self.name} matched query.",
                },
            )
        except Exception as exc:
            return AgentResult(
                agent=self.name, ok=False, confidence=0.0,
                data={"error": str(exc)},
            )


# Auto-register when imported
def _register():
    from eli.cognition.agent_bus import _ALL_AGENTS
    if not any(a.name == "tvshowagent" for a in _ALL_AGENTS):
        _ALL_AGENTS.append(Tvshowagent())

_register()
