"""
eli.planning.goal_autogenesis
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Turn ELI's *own* computed signals into goals.

The autonomy stack (goal_store → due_goals → governed_goal_tick → proposal_queue)
was fully wired but the goal store was always empty, because nothing ever created
a goal autonomously — `create_goal` was operator-only. So the scheduler ticked
nothing. This module closes that gap: it reads the signals ELI already produces
every proactive tick (world-model awareness suggestions + recurring failure
patterns) and turns the high-value ones into governed goals.

Governance (deliberate — autonomy, not recklessness):
  * Every autogenerated goal is `autonomy_mode="proposal_only"`. It surfaces as a
    pending proposal via the existing governed_goal_tick → proposal_queue path;
    it NEVER auto-executes. ELI sets his own agenda; the user still approves the
    actions.
  * Deduped by a STABLE goal_id derived from the signal, so a recurring signal
    updates/keeps one goal instead of spamming new ones (idempotent).
  * Capped at MAX_AUTO_GOALS active autogenerated goals at once.
  * Thresholded: world suggestions >= 0.6 priority; recurring errors >= 5 hits
    (mirrors the 5x/10x self-heal escalation contract).
"""

from __future__ import annotations

import hashlib
import logging
from typing import Any, Dict, List, Optional

log = logging.getLogger(__name__)

MAX_AUTO_GOALS = 6
AUTO_TAG = "autogenerated"
_WORLD_MIN_PRIORITY = 0.6
_ERROR_MIN_COUNT = 5


def _stable_goal_id(kind: str, key: str) -> str:
    """Deterministic id so the same signal maps to the same goal (dedup)."""
    h = hashlib.sha1(f"{kind}|{key}".encode("utf-8")).hexdigest()[:12]
    return f"auto_{kind}_{h}"


def _candidates_from_world(world_suggestions: Optional[List[Dict[str, Any]]]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for ws in (world_suggestions or []):
        if not isinstance(ws, dict):
            continue
        action = str(ws.get("action") or "").strip()
        prio = float(ws.get("priority", 0.0) or 0.0)
        if not action or prio < _WORLD_MIN_PRIORITY:
            continue
        out.append({
            "kind": "world",
            "key": action,
            "title": f"Address: {action.replace('_', ' ').lower()}",
            "objective": str(ws.get("reason") or f"My world-model flagged {action} as needed."),
            "priority": min(1.0, prio),
            "cadence_sec": 3600,
            "tags": [AUTO_TAG, "world_driven", action.lower()],
        })
    return out


def _candidates_from_patterns(patterns: Optional[List[Dict[str, Any]]]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for p in (patterns or []):
        if not isinstance(p, dict) or p.get("type") != "recurring_error":
            continue
        err = str(p.get("error") or "").strip()
        cnt = int(p.get("count", 0) or 0)
        if not err or cnt < _ERROR_MIN_COUNT:
            continue
        out.append({
            "kind": "recurring_error",
            "key": err[:80],
            "title": f"Resolve recurring failure ({cnt}x)",
            "objective": f"Diagnose and fix the recurring failure I keep hitting: {err[:160]}",
            "priority": min(0.95, 0.5 + cnt * 0.03),
            "cadence_sec": 7200,
            "tags": [AUTO_TAG, "self_repair"],
        })
    return out


def propose_goals_from_signals(
    world_suggestions: Optional[List[Dict[str, Any]]] = None,
    patterns: Optional[List[Dict[str, Any]]] = None,
    max_new: int = 3,
    memory: Any = None,
) -> List[str]:
    """Create governed goals from ELI's own signals. Returns the goal_ids created.

    Idempotent: a signal already tracked by an existing goal is skipped, so this is
    safe to call every proactive tick. Never raises.
    """
    created: List[str] = []
    try:
        from eli.planning.goal_store import load_goals, upsert_goal
        from eli.planning.goal_models import GoalSpec

        existing = list(load_goals())
        existing_ids = {g.goal_id for g in existing}
        auto_active = [
            g for g in existing
            if AUTO_TAG in (getattr(g, "tags", None) or [])
            and getattr(g, "enabled", True)
            and str(getattr(g, "status", "active")).lower() in {"active", "queued", "running"}
        ]
        room = MAX_AUTO_GOALS - len(auto_active)
        if room <= 0:
            return created

        candidates = _candidates_from_world(world_suggestions) + _candidates_from_patterns(patterns)
        # Highest-priority signals first.
        candidates.sort(key=lambda c: c["priority"], reverse=True)

        for c in candidates:
            if len(created) >= min(room, max_new):
                break
            gid = _stable_goal_id(c["kind"], c["key"])
            if gid in existing_ids:
                continue  # already a goal for this exact signal — don't churn
            spec = GoalSpec.from_any({
                "goal_id": gid,
                "title": c["title"],
                "objective": c["objective"],
                "priority": c["priority"],
                "cadence_sec": c["cadence_sec"],
                "autonomy_mode": "proposal_only",
                "tags": c["tags"],
                "enabled": True,
                "status": "active",
            })
            upsert_goal(spec)
            existing_ids.add(gid)
            created.append(gid)
            log.info("[GOAL_AUTOGENESIS] new goal %s — %s", gid, c["title"])
            # Transparency: record that ELI set himself a goal, so it surfaces in
            # reflection/overlay and the user can see his agenda forming.
            if memory is not None:
                try:
                    memory.add_observation(
                        source="goal_autogenesis",
                        category="self_goal",
                        observation=f"I set myself a goal: {c['title']}",
                        content=c["objective"],
                    )
                except Exception:
                    pass
    except Exception as exc:
        log.debug("[GOAL_AUTOGENESIS] failed: %s", exc)
    return created


__all__ = ["propose_goals_from_signals", "MAX_AUTO_GOALS", "AUTO_TAG"]
