"""
eli.planning.goal_autogenesis
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Turn ELI's *own* computed signals into goals.

The autonomy stack (goal_store → due_goals → governed_goal_tick → proposal_queue)
was fully wired but the goal store was always empty, because nothing ever created
a goal autonomously — `create_goal` was operator-only. So the scheduler ticked
nothing. This module closes that gap: it reads the signals ELI already produces
every proactive tick (world-model awareness suggestions + recurring failure
patterns) and turns the high-value ones into governed goals.

Governance (deliberate — autonomy, not recklessness):
  * Every autogenerated goal is `autonomy_mode="proposal_only"`. It surfaces as a
    pending proposal via the existing governed_goal_tick → proposal_queue path;
    it NEVER auto-executes. ELI sets his own agenda; the user still approves the
    actions.
  * Deduped by a STABLE goal_id derived from the signal, so a recurring signal
    updates/keeps one goal instead of spamming new ones (idempotent).
  * Capped at MAX_AUTO_GOALS active autogenerated goals at once.
  * Thresholded: world suggestions >= 0.6 priority; recurring errors >= 5 hits
    (mirrors the 5x/10x self-heal escalation contract).
"""

from __future__ import annotations

import hashlib
import logging
from typing import Any, Dict, List, Optional

log = logging.getLogger(__name__)

MAX_AUTO_GOALS = 6
AUTO_TAG = "autogenerated"
_WORLD_MIN_PRIORITY = 0.6
_ERROR_MIN_COUNT = 5


def _stable_goal_id(kind: str, key: str) -> str:
    """Deterministic id so the same signal maps to the same goal (dedup)."""
    h = hashlib.sha1(f"{kind}|{key}".encode("utf-8")).hexdigest()[:12]
    return f"auto_{kind}_{h}"


def _candidates_from_world(world_suggestions: Optional[List[Dict[str, Any]]]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for ws in (world_suggestions or []):
        if not isinstance(ws, dict):
            continue
        action = str(ws.get("action") or "").strip()
        prio = float(ws.get("priority", 0.0) or 0.0)
        if not action or prio < _WORLD_MIN_PRIORITY:
            continue
        out.append({
            "kind": "world",
            "key": action,
            "title": f"Address: {action.replace('_', ' ').lower()}",
            "objective": str(ws.get("reason") or f"My world-model flagged {action} as needed."),
            "priority": min(1.0, prio),
            "cadence_sec": 3600,
            "tags": [AUTO_TAG, "world_driven", action.lower()],
        })
    return out


_FREQ_BEHAVIOR_MIN_COUNT = int(__import__("os").environ.get("ELI_FREQ_HABIT_MIN", "8") or 8)


def _candidates_from_patterns(patterns: Optional[List[Dict[str, Any]]]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for p in (patterns or []):
        if not isinstance(p, dict):
            continue
        ptype = p.get("type")
        if ptype == "recurring_error":
            err = str(p.get("error") or "").strip()
            cnt = int(p.get("count", 0) or 0)
            if not err or cnt < _ERROR_MIN_COUNT:
                continue
            out.append({
                "kind": "recurring_error",
                "key": err[:80],
                "title": f"Resolve recurring failure ({cnt}x)",
                "objective": f"Diagnose and fix the recurring failure I keep hitting: {err[:160]}",
                "priority": min(0.95, 0.5 + cnt * 0.03),
                "cadence_sec": 7200,
                "tags": [AUTO_TAG, "self_repair"],
            })
        elif ptype == "frequent_behavior":
            # A high-frequency behaviour the user repeats but that never became a
            # time-scheduled rule (screenshots, media, news). Make ELI proactively OFFER
            # to streamline it — so curiosity about the user's routine produces an actual
            # proposal instead of dying as passive observation noise.
            beh = str(p.get("behavior") or "").strip()
            cnt = int(p.get("count", 0) or 0)
            if not beh or cnt < _FREQ_BEHAVIOR_MIN_COUNT:
                continue
            label = beh.replace("_", " ").lower()
            out.append({
                "kind": "frequent_behavior",
                "key": beh[:60],
                "title": f"Offer to streamline frequent '{label}'",
                "objective": (
                    f"The user does '{label}' often ({cnt}x recently). Proactively offer a "
                    f"faster path — a shortcut, a saved habit, or an automation — and ask "
                    f"before setting anything up."
                ),
                "priority": min(0.7, 0.4 + cnt * 0.01),
                "cadence_sec": 43200,
                "tags": [AUTO_TAG, "proactive", "habit"],
            })
    return out


def _candidates_from_improvements(improvements: Optional[List[Dict[str, Any]]]) -> List[Dict[str, Any]]:
    """Code-health signals ELI computes about its OWN code → self-betterment goals.
    Generative (not just failure-reactive): proposes refactors of its own god-files.
    Thresholded so only significant issues become goals (TODO noise is excluded)."""
    out: List[Dict[str, Any]] = []
    for im in (improvements or []):
        if not isinstance(im, dict):
            continue
        itype = str(im.get("type") or "")
        f = str(im.get("file") or "?")
        sugg = str(im.get("suggestion") or "")
        if itype == "long_function" and int(im.get("lines", 0) or 0) >= 150:
            fn = str(im.get("function") or "?")
            out.append({
                "kind": "improve",
                "key": f"long_function:{f}:{fn}",
                "title": f"Refactor my oversized function {fn}() in {f}",
                "objective": sugg or f"Split the {im.get('lines')}-line function {fn} in {f}.",
                "priority": 0.5,
                "cadence_sec": 86400,
                "tags": [AUTO_TAG, "self_improve", "code_health"],
            })
        elif itype == "duplicate_code" and int(im.get("count", 0) or 0) >= 5:
            out.append({
                "kind": "improve",
                "key": f"duplicate_code:{f}",
                "title": f"De-duplicate repeated blocks in my {f}",
                "objective": sugg or f"Refactor {im.get('count')} duplicate blocks in {f}.",
                "priority": 0.55,
                "cadence_sec": 86400,
                "tags": [AUTO_TAG, "self_improve", "code_health"],
            })
    return out


def propose_goals_from_signals(
    world_suggestions: Optional[List[Dict[str, Any]]] = None,
    patterns: Optional[List[Dict[str, Any]]] = None,
    improvements: Optional[List[Dict[str, Any]]] = None,
    max_new: int = 3,
    memory: Any = None,
) -> List[str]:
    """Create governed goals from ELI's own signals. Returns the goal_ids created.

    Idempotent: a signal already tracked by an existing goal is skipped, so this is
    safe to call every proactive tick. Never raises.
    """
    created: List[str] = []
    try:
        from eli.planning.goal_store import load_goals, upsert_goal
        from eli.planning.goal_models import GoalSpec

        existing = list(load_goals())
        existing_ids = {g.goal_id for g in existing}
        auto_active = [
            g for g in existing
            if AUTO_TAG in (getattr(g, "tags", None) or [])
            and getattr(g, "enabled", True)
            and str(getattr(g, "status", "active")).lower() in {"active", "queued", "running"}
        ]
        room = MAX_AUTO_GOALS - len(auto_active)
        if room <= 0:
            return created

        candidates = (
            _candidates_from_world(world_suggestions)
            + _candidates_from_patterns(patterns)
            + _candidates_from_improvements(improvements)
        )
        # Highest-priority signals first.
        candidates.sort(key=lambda c: c["priority"], reverse=True)

        for c in candidates:
            if len(created) >= min(room, max_new):
                break
            gid = _stable_goal_id(c["kind"], c["key"])
            if gid in existing_ids:
                continue  # already a goal for this exact signal — don't churn
            spec = GoalSpec.from_any({
                "goal_id": gid,
                "title": c["title"],
                "objective": c["objective"],
                "priority": c["priority"],
                "cadence_sec": c["cadence_sec"],
                "autonomy_mode": "proposal_only",
                "tags": c["tags"],
                "enabled": True,
                "status": "active",
            })
            upsert_goal(spec)
            existing_ids.add(gid)
            created.append(gid)
            log.info("[GOAL_AUTOGENESIS] new goal %s — %s", gid, c["title"])
            # Transparency: record that ELI set himself a goal, so it surfaces in
            # reflection/overlay and the user can see his agenda forming.
            if memory is not None:
                try:
                    memory.add_observation(
                        source="goal_autogenesis",
                        category="self_goal",
                        observation=f"I set myself a goal: {c['title']}",
                        content=c["objective"],
                    )
                except Exception:
                    pass
    except Exception as exc:
        log.debug("[GOAL_AUTOGENESIS] failed: %s", exc)
    return created


__all__ = ["propose_goals_from_signals", "MAX_AUTO_GOALS", "AUTO_TAG"]
