#!/usr/bin/env bash
# ELI MKXI — hardened Linux install helper
# Fresh venv, secret rotation, conservative defaults for solo offline use.
#
# Usage (from repo root):
#   bash scripts/safe_install_linux.sh
#   bash scripts/safe_install_linux.sh --skip-deps    # venv + harden only
#   bash scripts/safe_install_linux.sh --gpu          # pass --gpu to install.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

SKIP_DEPS=0
INSTALL_ARGS=(--yes --no-model)
for arg in "$@"; do
  case "$arg" in
    --skip-deps) SKIP_DEPS=1 ;;
    --gpu)       INSTALL_ARGS=(--yes --no-model --gpu) ;;
    --cpu-only)  INSTALL_ARGS=(--yes --no-model --cpu-only) ;;
    *)           INSTALL_ARGS+=("$arg") ;;
  esac
done

if [ -t 1 ]; then
  B=$'\033[1m'; GRN=$'\033[32m'; YEL=$'\033[33m'; CYN=$'\033[36m'; R=$'\033[0m'
else
  B=; GRN=; YEL=; CYN=; R=
fi

info()  { echo "${CYN}[safe-install]${R} $*"; }
ok()    { echo "${GRN}[ok]${R} $*"; }
warn()  { echo "${YEL}[warn]${R} $*"; }

PYTHON="${PYTHON:-python3}"
VENV="$ROOT/.venv"

info "Repo: $ROOT"

# ── 1. Backup live secrets (if any) ─────────────────────────────────────────
STAMP="$(date +%Y%m%d_%H%M%S)"
BACKUP_DIR="$ROOT/artifacts/startup/safe_install_backup_$STAMP"
mkdir -p "$BACKUP_DIR"
for f in config/api_token config/.audit_hmac_key config/settings.json; do
  if [ -f "$ROOT/$f" ]; then
    cp -a "$ROOT/$f" "$BACKUP_DIR/"
    ok "Backed up $f → $BACKUP_DIR/"
  fi
done

# ── 2. Fresh virtualenv ───────────────────────────────────────────────────────
if [ -d "$VENV" ]; then
  warn "Removing existing .venv for a clean install"
  rm -rf "$VENV"
fi
info "Creating virtualenv with $PYTHON"
"$PYTHON" -m venv "$VENV"
# shellcheck disable=SC1091
source "$VENV/bin/activate"
python -m pip install --upgrade pip setuptools wheel
ok "Virtualenv ready: $VENV"

# ── 3. Install dependencies ───────────────────────────────────────────────────
if [ "$SKIP_DEPS" -eq 0 ]; then
  if [ -x "$ROOT/install.sh" ]; then
    info "Running install.sh ${INSTALL_ARGS[*]}"
    bash "$ROOT/install.sh" "${INSTALL_ARGS[@]}"
  else
    warn "install.sh not found — installing from requirements-full.txt"
    python -m pip install -r "$ROOT/requirements-full.txt"
    python -m pip install -e ".[full]"
  fi
else
  info "Skipping dependency install (--skip-deps)"
  python -m pip install -e ".[full]" 2>/dev/null || true
fi

# ── 4. Rotate secrets ─────────────────────────────────────────────────────────
info "Rotating API token and audit HMAC key"
ROOT="$ROOT" python - <<'PY'
import os, secrets, stat
from pathlib import Path

root = Path(os.environ["ROOT"])
cfg = root / "config"
cfg.mkdir(parents=True, exist_ok=True)

api_token = secrets.token_urlsafe(32)
(root / "config" / "api_token").write_text(api_token + "\n", encoding="utf-8")
os.chmod(root / "config" / "api_token", 0o600)

hmac_key = secrets.token_hex(32)
(root / "config" / ".audit_hmac_key").write_text(hmac_key + "\n", encoding="utf-8")
os.chmod(root / "config" / ".audit_hmac_key", 0o600)

print("New API token written to config/api_token (0600)")
print("New audit HMAC key written to config/.audit_hmac_key (0600)")
print("Export for clients:  export ELI_API_TOKEN=$(cat config/api_token)")
PY

# ── 5. Harden settings.json ───────────────────────────────────────────────────
info "Applying hardened defaults to config/settings.json"
ROOT="$ROOT" python - <<'PY'
import json, os
from pathlib import Path

root = Path(os.environ["ROOT"])
settings_path = root / "config" / "settings.json"
example_path = root / "config" / "settings.example.json"

if settings_path.exists():
    data = json.loads(settings_path.read_text(encoding="utf-8"))
elif example_path.exists():
    data = json.loads(example_path.read_text(encoding="utf-8"))
else:
    data = {}

harden = {
    "full_control": False,
    "network_enabled": False,
    "auto_patch_enabled": False,
    "habit_shell_enabled": False,
    "allow_direct_chat_without_wake": False,
    "gaze_engine_enabled": False,
    "ambient_vision_enabled": False,
    "auto_speak": False,
    "mic_enabled": False,
}
data.update(harden)
settings_path.parent.mkdir(parents=True, exist_ok=True)
settings_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
os.chmod(settings_path, 0o600)
print("Hardened settings written:")
for k, v in harden.items():
    print(f"  {k} = {v}")
PY

# ── 6. Env helper (optional, not auto-sourced) ────────────────────────────────
ENV_FILE="$ROOT/config/safe_install.env"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/safe_install_linux.sh — source before launching ELI
export ELI_PROJECT_ROOT="$ROOT"
export ELI_API_ALLOW_TOKENLESS=0
# Do NOT set ELI_ALLOWED_CMDS unless you intend to allow shell commands.
# unset ELI_ALLOWED_CMDS
EOF
chmod 0600 "$ENV_FILE"
ok "Wrote $ENV_FILE"

# ── 7. Quick sanity checks ────────────────────────────────────────────────────
info "Running security smoke tests (API + shell gate)"
python -m pytest -q \
  tests/test_api_security.py \
  tests/test_shell_security_gate.py \
  --tb=no -x 2>/dev/null && ok "Security tests passed" || warn "Some security tests failed — review output"

echo
echo "${B}Safe install complete.${R}"
echo "  Activate:  source $VENV/bin/activate"
echo "  Harden:    source $ENV_FILE"
echo "  Launch:    ./scripts/eli_launch.sh"
echo "  API token: cat config/api_token"
echo
echo "Defaults applied: offline network, Full Control OFF, auto-patch OFF,"
echo "habit shell OFF, mic/gaze/ambient vision OFF."
echo "Re-enable features individually in Settings after you trust the install."
